Rails.application.routes.draw do
  root "articles#index"

  # get "/articles", to: "articles#index"
  # get "/articles/:id", to: "articles#show"

  # resourceful routing 
  resources :articles
  # We can see the routes generated by using rails routes on the console
  
  # Prefix        Verb      URI Pattern                     Controller#Action
  # root          GET       /                               articles#index
  # articles      GET       /articles(.:format)             articles#index
  #               POST      /articles(.:format)             articles#create
  # new_article   GET       /articles/new(.:format)         articles#new
  # edit_article  GET       /articles/:id/edit(.:format)    articles#edit
  # article       GET       /articles/:id(.:format)         articles#show
  #               PATCH     /articles/:id(.:format)         articles#update
  #               PUT       /articles/:id(.:format)         articles#update
  #               DELETE    /articles/:id(.:format)         articles#destroy


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
